# Script to create phyloseq objects from COSQ data
# Should be run from the results folder, using the metabar_2021 environment

## Load packages
library(phyloseq)
library(tibble)
library(dplyr)
library(ggplot2)

## Loading metadata:
samples_df <- read.table("metadata/no_control_no_sing_samples_cleaned_metadata_ASV_wise.txt", sep="\t", header=T, row.names=1)
## Construct phyloseq metadata table
samples=sample_data(samples_df)

## Loading final table incl. taxonomy and OTU table
COSQ_all <- read.table("COSQ_final_dataset_cleaned_pident_70.tsv", sep="\t", header=T, row.names=1,check.names=F)
### Subset to metazoans with best hit(s) to only a single species
metazoa_100<-COSQ_all[which(COSQ_all$kingdom=="Metazoa" & COSQ_all$species_score==100),] # Remember that some MOTUs might be excluded due to tiny deviance from 100 due to computational inaccurracy
### Subset further to MOTUs with at least 97% similarity to best hit
metazoa_100_97<-metazoa_100[which(as.numeric(metazoa_100$pident.max.best)>=97),]
### Subset further to MOTUS with at least 10 ASVs
COSQ<-metazoa_100_97[which(as.numeric(metazoa_100_97$cluster_weight)>=10),]

## Create OTU table
### First check where the first sample column is
COSQ[1,1:28]
### Check that the last column is a sample column
n<-ncol(COSQ)
COSQ[1,(n-1):n]
### Extract all sample columns
COSQ_otu <- COSQ[,28:n] 
### Transform to a matrix
COSQ_otu_m <- as.matrix(COSQ_otu) 
### Construct phyloseq OTU table
OTU = otu_table(COSQ_otu_m,taxa_are_rows=TRUE) 

## Create Taxonomy table
### Extract relevant columns from the COSQ table. Notes: Cols8-14 = taxonomy, Col26 = score.id
COSQ_tax <- COSQ[,c(8:14,26)] 
### Transform to a matrix
COSQ_tax_m <- as.matrix(COSQ_tax) 
### Construct phyloseq taxonomy table
TAX = tax_table(COSQ_tax_m)

## Combine metadata, OTU sample and taxonomy into one experiment-level phyloseq object
COSQ_final <- phyloseq(OTU,TAX,samples) 
COSQ_final

## Merge samples from the same sample cluster to allow estimating frequency of taxa (in terms of presence in X no. of clusters)
merged = merge_samples(COSQ_final, "cluster")
SD = merge_samples(sample_data(COSQ_final), "cluster")
print(SD)
print(merged)
sample_names(COSQ_final)
sample_names(merged)
identical(SD, sample_data(merged))
## The OTU abundances of merged samples are summed
## Check by looking at just the top10 most abundant OTUs
OTUnames10 = names(sort(taxa_sums(COSQ_final), TRUE)[1:10])
GP10 = prune_taxa(OTUnames10, COSQ_final)
mGP10 = prune_taxa(OTUnames10, merged)
C11_samples = sample_names(subset(sample_data(COSQ_final), cluster=="11"))
print(C11_samples)
otu_table(GP10)[, C11_samples]
rowSums(otu_table(GP10)[, C11_samples])
otu_table(mGP10)["11",]

## Count for each taxon the number of clusters where it is present
no_clusters<-colSums(merged@otu_table != 0)
## Count how many taxa are present in at least 10, 15 and 20 clusters
ten_c<-no_clusters[no_clusters>=10]
length(ten_c)
fifteen_c<-no_clusters[no_clusters>=15]
length(fifteen_c)
twenty_c<-no_clusters[no_clusters>=20]
length(twenty_c)

## Make list of MOTUs present in at least 20 clusters
selection<-names(twenty_c)
## Extract these MOTUs from the COSQ table
COSQ_select<-COSQ[which(row.names(COSQ) %in% selection),]
## Check that the right no of MOTUs were extracted
length(selection)
nrow(COSQ_select)
## Write subsetted table to file
COSQ_select$id<-row.names(COSQ_select)
write.table(COSQ_select,"COSQ_final_dataset_cleaned_pident_70_selected.tsv",sep="\t")